-- 코드를 입력하세요
SELECT
B.writer_id, G.nickname,CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2),
CONCAT(SUBSTRING(TLNO,1,3),'-',SUBSTRING(TLNO,4,4),'-',SUBSTRING(TLNO,8,4))
FROM USED_GOODS_BOARD as B JOIN USED_GOODS_USER as G
ON B.writer_id = G.user_id
GROUP BY WRITER_ID HAVING COUNT(*)>=3
ORDER BY B.writer_id desc;