-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(AMOUNT)*PRICE as TOTAL_SALES
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE YEAR(O.PRODUCE_DATE)='2022' and MONTH(O.PRODUCE_DATE)='5'
GROUP BY O.PRODUCT_ID
order by TOTAL_SALES desc,P.PRODUCT_ID;



# SELECT *, sum(AMOUNT) FROM FOOD_ORDER WHERE YEAR(PRODUCE_DATE)='2022' and MONTH(PRODUCE_DATE)='5'
# GROUP BY PRODUCT_ID;
# SELECT * from food_product;